apiVersion: v1
kind: Pod
metadata:
  name: my-microservices-kubernetes
  labels:
    app: my-microservices-kubernetes
spec:
  containers:
    - image: tutum/hello-world
      name: hello-world
      ports:
        - containerPort: 8080