apiVersion: v1
kind: Service
metadata:
  name: "my-kubernetes-service"
  labels:
    app: "my-kubernetes-service"
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: 
    app: "my-kubernetes-service"
  type: LoadBalancer