apiVersion: v1
kind: ReplicationController
metadata:
  name: "my-kubernetes-rc"
  labels:
    app: "my-kubernetes-rc"
spec:
  replicas: 2
  selector: 
    app: "my-kubernetes-rc"
  template:
    metadata:
      labels:
        app: "my-kubernetes-rc"
    spec:
      containers:
        - image: tutum/hello-world
          name: "hello-world"
          ports:
            - containerPort: 8080
              name: http

